import asyncio
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession, async_sessionmaker
from sqlalchemy import text
from app.core.config import settings

async def seed_metadata():
    engine = create_async_engine(settings.DATABASE_URL, echo=False)
    ASL = async_sessionmaker(bind=engine, class_=AsyncSession)

    async with ASL() as db:
        print("Seeding sectors...")
        r = await db.execute(text("SELECT count(*) FROM sectors"))
        if r.scalar() == 0:
            for name, desc in [
                ("Mining", "Mining and mineral extraction projects"),
                ("Infrastructure", "Infrastructure development projects"),
                ("Industry", "Industrial manufacturing projects"),
            ]:
                await db.execute(
                    text("INSERT INTO sectors (name, description) VALUES (:name, :desc)"),
                    {"name": name, "desc": desc},
                )
                print(f"  Sector: {name}")

        await db.commit()

        # Get Mining sector ID
        r = await db.execute(text("SELECT id FROM sectors WHERE name = 'Mining'"))
        mining_id = r.scalar()
        print(f"  Mining id: {mining_id}")

        if mining_id:
            # Sector parameters
            r = await db.execute(
                text("SELECT count(*) FROM sector_parameters WHERE sector_id = :sid"),
                {"sid": mining_id},
            )
            if r.scalar() == 0:
                print("Seeding sector parameters...")
                params = [
                    ("Production Capacity", "production_capacity", "TEXT", True, 1),
                    ("Mine Area (sq km)", "mine_area", "NUMBER", True, 2),
                    ("Is Open Cast Mine", "is_open_cast", "BOOLEAN", False, 3),
                ]
                for name, key, ptype, req, order in params:
                    await db.execute(
                        text(
                            "INSERT INTO sector_parameters (sector_id, name, key, type, is_required, display_order) "
                            "VALUES (:sid, :name, :key, :type, :req, :ord)"
                        ),
                        {"sid": mining_id, "name": name, "key": key, "type": ptype, "req": req, "ord": order},
                    )
                print("  3 parameters created")

            # Gist template
            r = await db.execute(text("SELECT count(*) FROM gist_templates"))
            if r.scalar() == 0:
                print("Seeding gist template...")
                content = (
                    "PROJECT GIST\n\n"
                    "Project Name: {{project_name}}\n"
                    "Category: {{category}}\n\n"
                    "LOCATION:\n"
                    "  State: {{state}}, District: {{district}}\n"
                    "  Taluk: {{taluk}}, Village: {{village}}\n"
                    "  Pincode: {{pincode}}\n"
                    "  Coordinates: {{latitude}}, {{longitude}}\n\n"
                    "PROJECT DETAILS:\n"
                    "  Area: {{project_area_ha}} ha\n"
                    "  Capacity: {{capacity}}\n"
                    "  Production: {{production_capacity}}\n"
                    "  Mine Area: {{mine_area}} sq km\n"
                    "  Open Cast: {{is_open_cast}}\n\n"
                    "DESCRIPTION:\n{{project_description}}\n\n"
                    "---\nAuto-generated by Parivesh."
                )
                
                # Fetch an admin user id to serve as created_by
                r_user = await db.execute(text("SELECT id FROM users WHERE email='shasarita23@gmail.com'"))
                admin_id = r_user.scalar()
                
                if admin_id:
                    await db.execute(
                        text(
                            "INSERT INTO gist_templates (name, category, sector_id, content, version, is_active, created_by) "
                            "VALUES (:name, :cat, :sid, :content, 1, true, :uid)"
                        ),
                        {
                            "name": "Mining Cat-A Template",
                            "cat": "A",
                            "sid": mining_id,
                            "content": content,
                            "uid": admin_id,
                        },
                    )
                    print("  Template created")

        await db.commit()

    await engine.dispose()
    print("\n=== METADATA SEED COMPLETE ===")

if __name__ == "__main__":
    asyncio.run(seed_metadata())
