"""Create realistic, idempotent demo data that exercises all major workflows.

Usage:
  c:/Users/Asus/PycharmProject/Parivesh/.venv/Scripts/python.exe seed_demo_data.py
"""

import asyncio
from dataclasses import dataclass
from datetime import date, datetime, time, timedelta, timezone
from decimal import Decimal
from typing import Any

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

from app.core.config import settings
from app.core.eds_seed_data import get_ordered_points
from app.core.pp_undertaking_seed_data import get_ordered_undertaking_points
from app.core.security import get_password_hash


@dataclass(frozen=True)
class DemoUser:
    email: str
    password: str
    full_name: str
    organization: str
    phone: str
    role: str


DEMO_USERS = [
    DemoUser(
        email="admin@parivesh.demo",
        password="Admin@123",
        full_name="Ananya Verma",
        organization="MoEFCC Digital Cell",
        phone="9876500001",
        role="ADMIN",
    ),
    DemoUser(
        email="pp@parivesh.demo",
        password="PP@12345",
        full_name="Rohan Kulkarni",
        organization="EcoInfra Projects Pvt Ltd",
        phone="9876500002",
        role="PP",
    ),
    DemoUser(
        email="scrutiny@parivesh.demo",
        password="Scrutiny@123",
        full_name="Meera Nair",
        organization="Regional Clearance Cell",
        phone="9876500003",
        role="SCRUTINY",
    ),
    DemoUser(
        email="mom@parivesh.demo",
        password="MoM@12345",
        full_name="Arvind Menon",
        organization="EAC Secretariat",
        phone="9876500004",
        role="MOM",
    ),
]

SECTORS = [
    ("Mining", "Mining and mineral extraction projects"),
    ("Infrastructure", "Road, port and logistics infrastructure projects"),
    ("Industry", "Industrial manufacturing and process projects"),
]

SECTOR_PARAMS = {
    "Mining": [
        ("Production Capacity", "production_capacity", "TEXT", True, 1),
        ("Mine Area (sq km)", "mine_area", "NUMBER", True, 2),
        ("Is Open Cast Mine", "is_open_cast", "BOOLEAN", False, 3),
    ],
    "Infrastructure": [
        ("Construction Length (km)", "construction_length_km", "NUMBER", True, 1),
        ("Estimated Traffic (PCU/day)", "estimated_traffic_pcu", "NUMBER", True, 2),
        ("Includes Forest Patch", "includes_forest_patch", "BOOLEAN", False, 3),
    ],
    "Industry": [
        ("Annual Output", "annual_output", "TEXT", True, 1),
        ("Water Requirement (KLD)", "water_requirement_kld", "NUMBER", True, 2),
        ("Hazardous Waste Involved", "hazardous_waste", "BOOLEAN", False, 3),
    ],
}

GIST_TEMPLATE = (
    "PROJECT GIST\n\n"
    "Project Name: {{project_name}}\n"
    "Category: {{category}}\n\n"
    "LOCATION:\n"
    "  State: {{state}}, District: {{district}}\n"
    "  Taluk: {{taluk}}, Village: {{village}}\n"
    "  Pincode: {{pincode}}\n"
    "  Coordinates: {{latitude}}, {{longitude}}\n\n"
    "PROJECT DETAILS:\n"
    "  Area: {{project_area_ha}} ha\n"
    "  Capacity: {{capacity}}\n"
    "  Production: {{production_capacity}}\n"
    "  Mine Area: {{mine_area}} sq km\n"
    "  Open Cast: {{is_open_cast}}\n"
    "  Construction Length: {{construction_length_km}} km\n"
    "  Estimated Traffic: {{estimated_traffic_pcu}} PCU/day\n"
    "  Annual Output: {{annual_output}}\n"
    "  Water Requirement: {{water_requirement_kld}} KLD\n\n"
    "DESCRIPTION:\n{{project_description}}\n\n"
    "---\nAuto-generated by Parivesh Demo Seed."
)


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


async def scalar(db: AsyncSession, sql: str, params: dict[str, Any] | None = None) -> Any:
    result = await db.execute(text(sql), params or {})
    return result.scalar()


async def ensure_roles(db: AsyncSession) -> dict[str, int]:
    role_labels = {
        "ADMIN": "Administrator",
        "PP": "Project Proponent",
        "SCRUTINY": "Scrutiny Officer",
        "MOM": "Minutes of Meeting",
    }

    role_ids: dict[str, int] = {}
    for role_name, role_label in role_labels.items():
        role_id = await scalar(db, "SELECT id FROM roles WHERE name = :name", {"name": role_name})
        if not role_id:
            inserted = await db.execute(
                text(
                    "INSERT INTO roles (name, label) VALUES (:name, :label) RETURNING id"
                ),
                {"name": role_name, "label": role_label},
            )
            role_id = inserted.scalar_one()
        elif role_label:
            await db.execute(
                text("UPDATE roles SET label = :label WHERE id = :id"),
                {"id": role_id, "label": role_label},
            )
        role_ids[role_name] = int(role_id)

    return role_ids


async def ensure_users(db: AsyncSession, role_ids: dict[str, int]) -> dict[str, str]:
    user_ids: dict[str, str] = {}

    for demo_user in DEMO_USERS:
        user_id = await scalar(db, "SELECT id FROM users WHERE email = :email", {"email": demo_user.email})
        password_hash = get_password_hash(demo_user.password)

        if user_id:
            await db.execute(
                text(
                    """
                    UPDATE users
                    SET password_hash = :password_hash,
                        full_name = :full_name,
                        organization = :organization,
                        phone = :phone,
                        is_active = true
                    WHERE id = :user_id
                    """
                ),
                {
                    "user_id": user_id,
                    "password_hash": password_hash,
                    "full_name": demo_user.full_name,
                    "organization": demo_user.organization,
                    "phone": demo_user.phone,
                },
            )
        else:
            inserted = await db.execute(
                text(
                    """
                    INSERT INTO users (email, password_hash, full_name, organization, phone, is_active)
                    VALUES (:email, :password_hash, :full_name, :organization, :phone, true)
                    RETURNING id
                    """
                ),
                {
                    "email": demo_user.email,
                    "password_hash": password_hash,
                    "full_name": demo_user.full_name,
                    "organization": demo_user.organization,
                    "phone": demo_user.phone,
                },
            )
            user_id = inserted.scalar_one()

        role_id = role_ids[demo_user.role]
        link_exists = await scalar(
            db,
            "SELECT 1 FROM user_roles WHERE user_id = :user_id AND role_id = :role_id",
            {"user_id": user_id, "role_id": role_id},
        )
        if not link_exists:
            await db.execute(
                text("INSERT INTO user_roles (user_id, role_id) VALUES (:user_id, :role_id)"),
                {"user_id": user_id, "role_id": role_id},
            )

        user_ids[demo_user.role] = str(user_id)

    return user_ids


async def ensure_sectors_and_parameters(db: AsyncSession) -> tuple[dict[str, int], dict[str, dict[str, int]]]:
    sector_ids: dict[str, int] = {}
    param_ids_by_sector: dict[str, dict[str, int]] = {}

    for name, description in SECTORS:
        sector_id = await scalar(db, "SELECT id FROM sectors WHERE name = :name", {"name": name})
        if not sector_id:
            inserted = await db.execute(
                text("INSERT INTO sectors (name, description) VALUES (:name, :description) RETURNING id"),
                {"name": name, "description": description},
            )
            sector_id = inserted.scalar_one()
        else:
            await db.execute(
                text("UPDATE sectors SET description = :description WHERE id = :id"),
                {"id": sector_id, "description": description},
            )
        sector_ids[name] = int(sector_id)

        param_ids_by_sector[name] = {}
        for p_name, p_key, p_type, is_required, display_order in SECTOR_PARAMS[name]:
            param_id = await scalar(
                db,
                "SELECT id FROM sector_parameters WHERE sector_id = :sector_id AND key = :key",
                {"sector_id": sector_id, "key": p_key},
            )
            if not param_id:
                inserted = await db.execute(
                    text(
                        """
                        INSERT INTO sector_parameters
                            (sector_id, name, key, type, is_required, display_order)
                        VALUES
                            (:sector_id, :name, :key, :type, :is_required, :display_order)
                        RETURNING id
                        """
                    ),
                    {
                        "sector_id": sector_id,
                        "name": p_name,
                        "key": p_key,
                        "type": p_type,
                        "is_required": is_required,
                        "display_order": display_order,
                    },
                )
                param_id = inserted.scalar_one()
            else:
                await db.execute(
                    text(
                        """
                        UPDATE sector_parameters
                        SET name = :name,
                            type = :type,
                            is_required = :is_required,
                            display_order = :display_order
                        WHERE id = :id
                        """
                    ),
                    {
                        "id": param_id,
                        "name": p_name,
                        "type": p_type,
                        "is_required": is_required,
                        "display_order": display_order,
                    },
                )

            param_ids_by_sector[name][p_key] = int(param_id)

    return sector_ids, param_ids_by_sector


async def ensure_gist_templates(db: AsyncSession, admin_user_id: str, sector_ids: dict[str, int]) -> None:
    for sector_name, sector_id in sector_ids.items():
        for category in ("A", "B1", "B2"):
            template_name = f"{sector_name} {category} Demo Template"
            template_id = await scalar(
                db,
                "SELECT id FROM gist_templates WHERE name = :name AND sector_id = :sector_id",
                {"name": template_name, "sector_id": sector_id},
            )
            if template_id:
                await db.execute(
                    text(
                        """
                        UPDATE gist_templates
                        SET content = :content,
                            category = :category,
                            is_active = true,
                            version = 1,
                            created_by = :created_by
                        WHERE id = :id
                        """
                    ),
                    {
                        "id": template_id,
                        "content": GIST_TEMPLATE,
                        "category": category,
                        "created_by": admin_user_id,
                    },
                )
            else:
                await db.execute(
                    text(
                        """
                        INSERT INTO gist_templates
                            (name, category, sector_id, content, version, is_active, created_by)
                        VALUES
                            (:name, :category, :sector_id, :content, 1, true, :created_by)
                        """
                    ),
                    {
                        "name": template_name,
                        "category": category,
                        "sector_id": sector_id,
                        "content": GIST_TEMPLATE,
                        "created_by": admin_user_id,
                    },
                )


async def ensure_master_checklists(db: AsyncSession) -> None:
    for point in get_ordered_points():
        exists = await scalar(
            db,
            "SELECT 1 FROM eds_standard_points WHERE code = :code",
            {"code": point["code"]},
        )
        if not exists:
            await db.execute(
                text(
                    """
                    INSERT INTO eds_standard_points (code, label, category, display_order, is_active)
                    VALUES (:code, :label, :category, :display_order, true)
                    """
                ),
                {
                    "code": point["code"],
                    "label": point["label"],
                    "category": point["category"],
                    "display_order": point["display_order"],
                },
            )

    for point in get_ordered_undertaking_points():
        exists = await scalar(
            db,
            "SELECT 1 FROM pp_undertakings WHERE code = :code",
            {"code": point["code"]},
        )
        if not exists:
            await db.execute(
                text(
                    """
                    INSERT INTO pp_undertakings (code, label, mineral_type, display_order, is_active)
                    VALUES (:code, :label, :mineral_type, :display_order, true)
                    """
                ),
                {
                    "code": point["code"],
                    "label": point["label"],
                    "mineral_type": point["mineral_type"],
                    "display_order": point["display_order"],
                },
            )


async def ensure_meetings(db: AsyncSession, admin_user_id: str) -> dict[str, int]:
    meetings = {
        "EAC-95": {
            "meeting_date": date.today() - timedelta(days=10),
            "meeting_time": time(11, 30),
            "meeting_type": "EAC",
            "committee_name": "EAC-95",
        },
        "EAC-96": {
            "meeting_date": date.today() + timedelta(days=14),
            "meeting_time": time(10, 0),
            "meeting_type": "EAC",
            "committee_name": "EAC-96",
        },
    }

    ids: dict[str, int] = {}
    for key, payload in meetings.items():
        meeting_id = await scalar(
            db,
            "SELECT id FROM meetings WHERE committee_name = :committee_name AND meeting_date = :meeting_date",
            {
                "committee_name": payload["committee_name"],
                "meeting_date": payload["meeting_date"],
            },
        )
        if meeting_id:
            await db.execute(
                text(
                    """
                    UPDATE meetings
                    SET meeting_time = :meeting_time,
                        meeting_type = :meeting_type,
                        created_by = :created_by
                    WHERE id = :id
                    """
                ),
                {
                    "id": meeting_id,
                    "meeting_time": payload["meeting_time"],
                    "meeting_type": payload["meeting_type"],
                    "created_by": admin_user_id,
                },
            )
        else:
            inserted = await db.execute(
                text(
                    """
                    INSERT INTO meetings (meeting_date, meeting_time, meeting_type, committee_name, created_by)
                    VALUES (:meeting_date, :meeting_time, :meeting_type, :committee_name, :created_by)
                    RETURNING id
                    """
                ),
                {**payload, "created_by": admin_user_id},
            )
            meeting_id = inserted.scalar_one()

        ids[key] = int(meeting_id)

    return ids


async def upsert_application(
    db: AsyncSession,
    applicant_id: str,
    project_name: str,
    project_description: str,
    category: str,
    sector_id: int,
    status: str,
    state: str,
    district: str,
    taluk: str,
    village: str,
    pincode: str,
    latitude: Decimal,
    longitude: Decimal,
    project_area_ha: Decimal,
    capacity: str,
    risk_score: int,
    risk_level: str,
    eds_cycle_count: int,
    created_at: datetime,
) -> str:
    app_id = await scalar(
        db,
        "SELECT id FROM applications WHERE project_name = :project_name",
        {"project_name": project_name},
    )

    payload = {
        "applicant_id": applicant_id,
        "project_name": project_name,
        "project_description": project_description,
        "category": category,
        "sector_id": sector_id,
        "status": status,
        "state": state,
        "district": district,
        "taluk": taluk,
        "village": village,
        "pincode": pincode,
        "latitude": latitude,
        "longitude": longitude,
        "project_area_ha": project_area_ha,
        "capacity": capacity,
        "risk_score": risk_score,
        "risk_level": risk_level,
        "eds_cycle_count": eds_cycle_count,
        "created_at": created_at,
        "updated_at": utc_now(),
    }

    if app_id:
        await db.execute(
            text(
                """
                UPDATE applications
                SET applicant_id = :applicant_id,
                    project_description = :project_description,
                    category = :category,
                    sector_id = :sector_id,
                    status = :status,
                    state = :state,
                    district = :district,
                    taluk = :taluk,
                    village = :village,
                    pincode = :pincode,
                    latitude = :latitude,
                    longitude = :longitude,
                    project_area_ha = :project_area_ha,
                    capacity = :capacity,
                    risk_score = :risk_score,
                    risk_level = :risk_level,
                    eds_cycle_count = :eds_cycle_count,
                    updated_at = :updated_at
                WHERE id = :id
                """
            ),
            {**payload, "id": app_id},
        )
    else:
        inserted = await db.execute(
            text(
                """
                INSERT INTO applications
                    (applicant_id, project_name, project_description, category, sector_id,
                     state, district, taluk, village, pincode,
                     latitude, longitude, project_area_ha, capacity,
                     status, eds_cycle_count, risk_score, risk_level, created_at, updated_at)
                VALUES
                    (:applicant_id, :project_name, :project_description, :category, :sector_id,
                     :state, :district, :taluk, :village, :pincode,
                     :latitude, :longitude, :project_area_ha, :capacity,
                     :status, :eds_cycle_count, :risk_score, :risk_level, :created_at, :updated_at)
                RETURNING id
                """
            ),
            payload,
        )
        app_id = inserted.scalar_one()

    return str(app_id)


async def replace_application_parameters(
    db: AsyncSession,
    app_id: str,
    param_ids: dict[str, int],
    values: dict[str, Any],
) -> None:
    await db.execute(
        text("DELETE FROM application_parameters WHERE application_id = :app_id"),
        {"app_id": app_id},
    )

    for key, param_id in param_ids.items():
        if key not in values:
            continue

        value = values[key]
        value_text = None
        value_number = None
        value_boolean = None

        if isinstance(value, bool):
            value_boolean = value
        elif isinstance(value, (int, float, Decimal)):
            value_number = Decimal(str(value))
        else:
            value_text = str(value)

        await db.execute(
            text(
                """
                INSERT INTO application_parameters
                    (application_id, sector_parameter_id, value_text, value_number, value_boolean)
                VALUES
                    (:application_id, :sector_parameter_id, :value_text, :value_number, :value_boolean)
                """
            ),
            {
                "application_id": app_id,
                "sector_parameter_id": param_id,
                "value_text": value_text,
                "value_number": value_number,
                "value_boolean": value_boolean,
            },
        )


async def replace_documents(db: AsyncSession, app_id: str, uploader_id: str) -> None:
    await db.execute(
        text("DELETE FROM application_documents WHERE application_id = :app_id"),
        {"app_id": app_id},
    )

    docs = [
        ("Pre-feasibility Report", "application/pdf", True),
        ("Form-1 Application", "application/pdf", True),
        ("Conceptual Plan Map", "image/png", False),
    ]
    for idx, (name, mime_type, verified) in enumerate(docs, start=1):
        file_path = f"https://demo-docs.parivesh.local/{app_id}/{idx}_{name.lower().replace(' ', '_')}.pdf"
        await db.execute(
            text(
                """
                INSERT INTO application_documents
                    (application_id, name, file_path, mime_type, uploaded_by, is_verified)
                VALUES
                    (:application_id, :name, :file_path, :mime_type, :uploaded_by, :is_verified)
                """
            ),
            {
                "application_id": app_id,
                "name": name,
                "file_path": file_path,
                "mime_type": mime_type,
                "uploaded_by": uploader_id,
                "is_verified": verified,
            },
        )


async def upsert_payment(
    db: AsyncSession,
    app_id: str,
    amount: Decimal,
    status: str,
    transaction_ref: str,
) -> None:
    payment_id = await scalar(
        db,
        "SELECT id FROM payments WHERE application_id = :app_id",
        {"app_id": app_id},
    )

    initiated_at = utc_now() - timedelta(days=1)
    verified_at = utc_now() if status == "VERIFIED" else None
    payload = {
        "application_id": app_id,
        "amount": amount,
        "status": status,
        "transaction_ref": transaction_ref,
        "gateway_payload": '{"method":"UPI_QR_SIM","provider":"DemoGateway"}',
        "initiated_at": initiated_at,
        "verified_at": verified_at,
        "updated_at": utc_now(),
    }

    if payment_id:
        await db.execute(
            text(
                """
                UPDATE payments
                SET amount = :amount,
                    status = :status,
                    transaction_ref = :transaction_ref,
                    gateway_payload = CAST(:gateway_payload AS jsonb),
                    initiated_at = :initiated_at,
                    verified_at = :verified_at,
                    updated_at = :updated_at
                WHERE id = :id
                """
            ),
            {**payload, "id": payment_id},
        )
    else:
        await db.execute(
            text(
                """
                INSERT INTO payments
                    (application_id, amount, status, transaction_ref, gateway_payload, initiated_at, verified_at)
                VALUES
                    (:application_id, :amount, :status, :transaction_ref, CAST(:gateway_payload AS jsonb), :initiated_at, :verified_at)
                """
            ),
            payload,
        )


async def replace_status_history(db: AsyncSession, app_id: str, entries: list[dict[str, Any]]) -> None:
    await db.execute(
        text("DELETE FROM application_status_history WHERE application_id = :app_id"),
        {"app_id": app_id},
    )

    for row in entries:
        await db.execute(
            text(
                """
                INSERT INTO application_status_history
                    (application_id, from_status, to_status, changed_by_user_id, changed_by_role, reason, created_at)
                VALUES
                    (:application_id, :from_status, :to_status, :changed_by_user_id, :changed_by_role, :reason, :created_at)
                """
            ),
            {
                "application_id": app_id,
                "from_status": row.get("from_status"),
                "to_status": row["to_status"],
                "changed_by_user_id": row.get("changed_by_user_id"),
                "changed_by_role": row.get("changed_by_role"),
                "reason": row.get("reason"),
                "created_at": row.get("created_at", utc_now()),
            },
        )


async def upsert_eds(db: AsyncSession, app_id: str, raised_by: str, resolved: bool) -> None:
    await db.execute(text("DELETE FROM eds_issues WHERE eds_request_id IN (SELECT id FROM eds_requests WHERE application_id = :app_id)"), {"app_id": app_id})
    await db.execute(text("DELETE FROM eds_requests WHERE application_id = :app_id"), {"app_id": app_id})

    resolved_at = utc_now() - timedelta(days=2) if resolved else None
    inserted = await db.execute(
        text(
            """
            INSERT INTO eds_requests (application_id, cycle_number, raised_by, general_comments, raised_at, resolved_at)
            VALUES (:application_id, 1, :raised_by, :general_comments, :raised_at, :resolved_at)
            RETURNING id
            """
        ),
        {
            "application_id": app_id,
            "raised_by": raised_by,
            "general_comments": "Please provide revised land-use map and wet-season baseline values.",
            "raised_at": utc_now() - timedelta(days=5),
            "resolved_at": resolved_at,
        },
    )
    eds_id = inserted.scalar_one()

    issue_rows = [
        {
            "standard_reason": "Baseline data mismatch",
            "affected_field": "project_area_ha",
            "comments": "Area in map annexure differs from form value.",
            "resolution_text": "Area reconciled in revised annexure V2." if resolved else None,
            "is_resolved": resolved,
        },
        {
            "standard_reason": "Missing supporting document",
            "affected_field": "Conceptual Plan Map",
            "comments": "Map legend and scale details were unreadable.",
            "resolution_text": "Uploaded clear GIS-generated map with legend." if resolved else None,
            "is_resolved": resolved,
        },
    ]

    for row in issue_rows:
        await db.execute(
            text(
                """
                INSERT INTO eds_issues
                    (eds_request_id, standard_reason, affected_field, comments, resolution_text, is_resolved)
                VALUES
                    (:eds_request_id, :standard_reason, :affected_field, :comments, :resolution_text, :is_resolved)
                """
            ),
            {**row, "eds_request_id": eds_id},
        )


async def upsert_referral(db: AsyncSession, app_id: str, meeting_id: int, scrutiny_user_id: str, notes: str) -> None:
    exists = await scalar(
        db,
        "SELECT 1 FROM meeting_applications WHERE meeting_id = :meeting_id AND application_id = :application_id",
        {"meeting_id": meeting_id, "application_id": app_id},
    )
    if exists:
        await db.execute(
            text(
                """
                UPDATE meeting_applications
                SET referral_notes = :referral_notes,
                    referred_by = :referred_by,
                    referred_at = :referred_at
                WHERE meeting_id = :meeting_id AND application_id = :application_id
                """
            ),
            {
                "meeting_id": meeting_id,
                "application_id": app_id,
                "referral_notes": notes,
                "referred_by": scrutiny_user_id,
                "referred_at": utc_now() - timedelta(days=2),
            },
        )
    else:
        await db.execute(
            text(
                """
                INSERT INTO meeting_applications
                    (meeting_id, application_id, referral_notes, referred_by, referred_at)
                VALUES
                    (:meeting_id, :application_id, :referral_notes, :referred_by, :referred_at)
                """
            ),
            {
                "meeting_id": meeting_id,
                "application_id": app_id,
                "referral_notes": notes,
                "referred_by": scrutiny_user_id,
                "referred_at": utc_now() - timedelta(days=2),
            },
        )


async def upsert_gist(db: AsyncSession, app_id: str, generated_by: str, content: str) -> int:
    gist_id = await scalar(
        db,
        "SELECT id FROM gists WHERE application_id = :application_id",
        {"application_id": app_id},
    )

    template_id = await scalar(
        db,
        "SELECT id FROM gist_templates WHERE is_active = true ORDER BY id LIMIT 1",
    )

    if gist_id:
        await db.execute(
            text(
                """
                UPDATE gists
                SET template_id = :template_id,
                    content = :content,
                    generated_by = :generated_by,
                    generated_at = :generated_at,
                    last_modified_by = :last_modified_by,
                    last_modified_at = :last_modified_at
                WHERE id = :id
                """
            ),
            {
                "id": gist_id,
                "template_id": template_id,
                "content": content,
                "generated_by": generated_by,
                "generated_at": utc_now() - timedelta(days=1),
                "last_modified_by": generated_by,
                "last_modified_at": utc_now() - timedelta(hours=4),
            },
        )
        return int(gist_id)

    inserted = await db.execute(
        text(
            """
            INSERT INTO gists
                (application_id, template_id, content, generated_by, generated_at, last_modified_by, last_modified_at)
            VALUES
                (:application_id, :template_id, :content, :generated_by, :generated_at, :last_modified_by, :last_modified_at)
            RETURNING id
            """
        ),
        {
            "application_id": app_id,
            "template_id": template_id,
            "content": content,
            "generated_by": generated_by,
            "generated_at": utc_now() - timedelta(days=1),
            "last_modified_by": generated_by,
            "last_modified_at": utc_now() - timedelta(hours=4),
        },
    )
    return int(inserted.scalar_one())


async def upsert_mom(
    db: AsyncSession,
    app_id: str,
    gist_id: int,
    created_by: str,
    finalized_by: str | None,
    status: str,
) -> None:
    mom_id = await scalar(db, "SELECT id FROM moms WHERE application_id = :application_id", {"application_id": app_id})

    content = (
        "MINUTES OF MEETING\n\n"
        f"Application ID: {app_id}\n"
        "Committee observed cumulative impact, mitigation commitments, and compliance timeline.\n"
        "Decision: Subject to conditions in annexure, proposal may proceed to next compliance stage.\n"
    )

    payload = {
        "application_id": app_id,
        "gist_id": gist_id,
        "content": content,
        "status": status,
        "integrity_hash": f"demo-{app_id[:8]}-{status.lower()}",
        "created_by": created_by,
        "created_at": utc_now() - timedelta(hours=18),
        "finalized_by": finalized_by,
        "finalized_at": utc_now() - timedelta(hours=2) if status == "FINALIZED" else None,
        "mom_docx_path": f"/generated/mom_{app_id}.docx",
        "mom_pdf_path": f"/generated/mom_{app_id}.pdf",
        "gist_docx_path": f"/generated/gist_{app_id}.docx",
        "gist_pdf_path": f"/generated/gist_{app_id}.pdf",
    }

    if mom_id:
        await db.execute(
            text(
                """
                UPDATE moms
                SET gist_id = :gist_id,
                    content = :content,
                    status = :status,
                    integrity_hash = :integrity_hash,
                    created_by = :created_by,
                    finalized_by = :finalized_by,
                    finalized_at = :finalized_at,
                    mom_docx_path = :mom_docx_path,
                    mom_pdf_path = :mom_pdf_path,
                    gist_docx_path = :gist_docx_path,
                    gist_pdf_path = :gist_pdf_path
                WHERE id = :id
                """
            ),
            {**payload, "id": mom_id},
        )
    else:
        await db.execute(
            text(
                """
                INSERT INTO moms
                    (application_id, gist_id, content, status, integrity_hash, created_by, created_at,
                     finalized_by, finalized_at, mom_docx_path, mom_pdf_path, gist_docx_path, gist_pdf_path)
                VALUES
                    (:application_id, :gist_id, :content, :status, :integrity_hash, :created_by, :created_at,
                     :finalized_by, :finalized_at, :mom_docx_path, :mom_pdf_path, :gist_docx_path, :gist_pdf_path)
                """
            ),
            payload,
        )


async def append_audit_snapshot(db: AsyncSession, actor_id: str, actor_role: str, app_id: str, status: str) -> None:
    exists = await scalar(
        db,
        "SELECT 1 FROM audit_logs WHERE action = :action AND entity_id = :entity_id",
        {"action": f"DEMO_{status}", "entity_id": app_id},
    )
    if exists:
        return

    await db.execute(
        text(
            """
            INSERT INTO audit_logs
                (actor_id, actor_role, action, description, entity_type, entity_id, ip_address)
            VALUES
                (:actor_id, :actor_role, :action, :description, 'APPLICATION', :entity_id, CAST(:ip_address AS inet))
            """
        ),
        {
            "actor_id": actor_id,
            "actor_role": actor_role,
            "action": f"DEMO_{status}",
            "description": f"Demo data seeded for application in {status} state.",
            "entity_id": app_id,
            "ip_address": "127.0.0.1",
        },
    )


async def seed_demo_data() -> None:
    engine = create_async_engine(settings.DATABASE_URL, echo=False)
    session_factory = async_sessionmaker(bind=engine, class_=AsyncSession, expire_on_commit=False)

    async with session_factory() as db:
        role_ids = await ensure_roles(db)
        user_ids = await ensure_users(db, role_ids)
        sector_ids, param_ids_by_sector = await ensure_sectors_and_parameters(db)
        await ensure_master_checklists(db)
        await ensure_gist_templates(db, user_ids["ADMIN"], sector_ids)
        meeting_ids = await ensure_meetings(db, user_ids["ADMIN"])

        app_blueprints = [
            {
                "project_name": "Demo | Riverbend Limestone Expansion",
                "description": "Expansion of captive limestone mine with upgraded haul road and dust suppression system.",
                "category": "A",
                "sector": "Mining",
                "status": "DRAFT",
                "risk_score": 28,
                "risk_level": "LOW",
                "eds_cycle_count": 0,
                "location": ("Rajasthan", "Chittorgarh", "Nimbahera", "Bassi", "312601"),
                "coordinates": (Decimal("24.8792411"), Decimal("74.6511132")),
                "area": Decimal("126.4500"),
                "capacity": "1.8 MTPA",
                "params": {
                    "production_capacity": "1.8 MTPA",
                    "mine_area": Decimal("8.75"),
                    "is_open_cast": True,
                },
                "days_ago": 2,
                "payment": None,
            },
            {
                "project_name": "Demo | Eastern Freight Corridor Logistics Hub",
                "description": "Integrated multimodal logistics park with rail siding and truck terminal.",
                "category": "B1",
                "sector": "Infrastructure",
                "status": "SUBMITTED",
                "risk_score": 43,
                "risk_level": "MEDIUM",
                "eds_cycle_count": 0,
                "location": ("Maharashtra", "Nagpur", "Kamptee", "Borgaon", "441122"),
                "coordinates": (Decimal("21.1662830"), Decimal("79.0824510")),
                "area": Decimal("84.2000"),
                "capacity": "0.35 MTPA cargo handling",
                "params": {
                    "construction_length_km": Decimal("12.4"),
                    "estimated_traffic_pcu": Decimal("15800"),
                    "includes_forest_patch": False,
                },
                "days_ago": 5,
                "payment": None,
            },
            {
                "project_name": "Demo | GreenCem Clinker Unit Modernization",
                "description": "Retrofitting old clinker line with low-NOx burners and WHRS integration.",
                "category": "B2",
                "sector": "Industry",
                "status": "UNDER_SCRUTINY",
                "risk_score": 56,
                "risk_level": "MEDIUM",
                "eds_cycle_count": 0,
                "location": ("Gujarat", "Kutch", "Bhuj", "Mundra", "370421"),
                "coordinates": (Decimal("22.8390990"), Decimal("69.7190810")),
                "area": Decimal("42.8000"),
                "capacity": "0.9 MTPA clinker",
                "params": {
                    "annual_output": "0.9 MTPA clinker",
                    "water_requirement_kld": Decimal("420"),
                    "hazardous_waste": True,
                },
                "days_ago": 8,
                "payment": (Decimal("75000.00"), "PENDING", "UPI-SIM-UNDERSCRUTINY"),
            },
            {
                "project_name": "Demo | Kaveri M-Sand Cluster",
                "description": "Cluster-based M-sand extraction and beneficiation plant near river terrace.",
                "category": "B1",
                "sector": "Mining",
                "status": "EDS",
                "risk_score": 68,
                "risk_level": "HIGH",
                "eds_cycle_count": 1,
                "location": ("Karnataka", "Mandya", "Srirangapatna", "Arakere", "571415"),
                "coordinates": (Decimal("12.4235230"), Decimal("76.6947500")),
                "area": Decimal("63.9000"),
                "capacity": "1.1 MTPA",
                "params": {
                    "production_capacity": "1.1 MTPA",
                    "mine_area": Decimal("5.15"),
                    "is_open_cast": False,
                },
                "days_ago": 11,
                "payment": (Decimal("92500.00"), "PENDING", "UPI-SIM-EDSCASE-001"),
            },
            {
                "project_name": "Demo | Narmada Hydel Tailrace Improvement",
                "description": "Hydraulic and civil upgrades for tailrace channel stabilization and flood routing.",
                "category": "A",
                "sector": "Infrastructure",
                "status": "REFERRED",
                "risk_score": 72,
                "risk_level": "HIGH",
                "eds_cycle_count": 1,
                "location": ("Madhya Pradesh", "Khandwa", "Punasa", "Mundi", "450112"),
                "coordinates": (Decimal("22.2596300"), Decimal("76.4706500")),
                "area": Decimal("131.0000"),
                "capacity": "420 MW support infrastructure",
                "params": {
                    "construction_length_km": Decimal("6.8"),
                    "estimated_traffic_pcu": Decimal("9200"),
                    "includes_forest_patch": True,
                },
                "days_ago": 14,
                "payment": (Decimal("118000.00"), "VERIFIED", "UPI-SIM-REFERRED-204"),
            },
            {
                "project_name": "Demo | Satpura Bauxite Expansion Phase II",
                "description": "Expansion phase with conveyorized transport and advanced surface water drains.",
                "category": "A",
                "sector": "Mining",
                "status": "MOM_GENERATED",
                "risk_score": 63,
                "risk_level": "MEDIUM",
                "eds_cycle_count": 1,
                "location": ("Odisha", "Koraput", "Laxmipur", "Tikiri", "765015"),
                "coordinates": (Decimal("19.1357210"), Decimal("83.1086120")),
                "area": Decimal("154.3200"),
                "capacity": "2.2 MTPA",
                "params": {
                    "production_capacity": "2.2 MTPA",
                    "mine_area": Decimal("12.45"),
                    "is_open_cast": True,
                },
                "days_ago": 18,
                "payment": (Decimal("136500.00"), "VERIFIED", "UPI-SIM-MOMGIST-405"),
            },
            {
                "project_name": "Demo | Coastal Port Berth Deepening Project",
                "description": "Dredging and berth strengthening package to handle larger vessel classes safely.",
                "category": "A",
                "sector": "Infrastructure",
                "status": "FINALIZED",
                "risk_score": 77,
                "risk_level": "HIGH",
                "eds_cycle_count": 1,
                "location": ("Tamil Nadu", "Thoothukudi", "Tiruchendur", "Mullakadu", "628005"),
                "coordinates": (Decimal("8.7519200"), Decimal("78.1348300")),
                "area": Decimal("205.6000"),
                "capacity": "18 MTPA cargo",
                "params": {
                    "construction_length_km": Decimal("4.1"),
                    "estimated_traffic_pcu": Decimal("12100"),
                    "includes_forest_patch": False,
                },
                "days_ago": 26,
                "payment": (Decimal("158750.00"), "VERIFIED", "UPI-SIM-FINAL-889"),
            },
        ]

        for spec in app_blueprints:
            state, district, taluk, village, pincode = spec["location"]
            created_at = utc_now() - timedelta(days=spec["days_ago"])
            app_id = await upsert_application(
                db=db,
                applicant_id=user_ids["PP"],
                project_name=spec["project_name"],
                project_description=spec["description"],
                category=spec["category"],
                sector_id=sector_ids[spec["sector"]],
                status=spec["status"],
                state=state,
                district=district,
                taluk=taluk,
                village=village,
                pincode=pincode,
                latitude=spec["coordinates"][0],
                longitude=spec["coordinates"][1],
                project_area_ha=spec["area"],
                capacity=spec["capacity"],
                risk_score=spec["risk_score"],
                risk_level=spec["risk_level"],
                eds_cycle_count=spec["eds_cycle_count"],
                created_at=created_at,
            )

            await replace_application_parameters(
                db,
                app_id,
                param_ids_by_sector[spec["sector"]],
                spec["params"],
            )
            await replace_documents(db, app_id, user_ids["PP"])

            if spec["payment"] is not None:
                amount, pay_status, txn = spec["payment"]
                await upsert_payment(db, app_id, amount, pay_status, txn)
            else:
                await db.execute(
                    text("DELETE FROM payments WHERE application_id = :app_id"),
                    {"app_id": app_id},
                )

            history_entries = [
                {
                    "from_status": None,
                    "to_status": "DRAFT",
                    "changed_by_user_id": user_ids["PP"],
                    "changed_by_role": "PP",
                    "reason": "Application draft initiated.",
                    "created_at": created_at,
                }
            ]
            if spec["status"] != "DRAFT":
                history_entries.append(
                    {
                        "from_status": "DRAFT",
                        "to_status": "SUBMITTED",
                        "changed_by_user_id": user_ids["PP"],
                        "changed_by_role": "PP",
                        "reason": "Application submitted with required documents.",
                        "created_at": created_at + timedelta(days=1),
                    }
                )
            if spec["status"] in {"UNDER_SCRUTINY", "EDS", "REFERRED", "MOM_GENERATED", "FINALIZED"}:
                history_entries.append(
                    {
                        "from_status": "SUBMITTED",
                        "to_status": "UNDER_SCRUTINY",
                        "changed_by_user_id": user_ids["SCRUTINY"],
                        "changed_by_role": "SCRUTINY",
                        "reason": "Accepted for scrutiny queue.",
                        "created_at": created_at + timedelta(days=2),
                    }
                )
            if spec["status"] in {"EDS", "REFERRED", "MOM_GENERATED", "FINALIZED"}:
                history_entries.append(
                    {
                        "from_status": "UNDER_SCRUTINY",
                        "to_status": "EDS",
                        "changed_by_user_id": user_ids["SCRUTINY"],
                        "changed_by_role": "SCRUTINY",
                        "reason": "Clarifications requested via EDS.",
                        "created_at": created_at + timedelta(days=3),
                    }
                )
            if spec["status"] in {"REFERRED", "MOM_GENERATED", "FINALIZED"}:
                history_entries.append(
                    {
                        "from_status": "EDS",
                        "to_status": "UNDER_SCRUTINY",
                        "changed_by_user_id": user_ids["PP"],
                        "changed_by_role": "PP",
                        "reason": "EDS clarifications submitted.",
                        "created_at": created_at + timedelta(days=4),
                    }
                )
                history_entries.append(
                    {
                        "from_status": "UNDER_SCRUTINY",
                        "to_status": "REFERRED",
                        "changed_by_user_id": user_ids["SCRUTINY"],
                        "changed_by_role": "SCRUTINY",
                        "reason": "Payment verified and referred to EAC.",
                        "created_at": created_at + timedelta(days=5),
                    }
                )
            if spec["status"] in {"MOM_GENERATED", "FINALIZED"}:
                history_entries.append(
                    {
                        "from_status": "REFERRED",
                        "to_status": "MOM_GENERATED",
                        "changed_by_user_id": user_ids["SCRUTINY"],
                        "changed_by_role": "SCRUTINY",
                        "reason": "Gist generated for meeting documentation.",
                        "created_at": created_at + timedelta(days=6),
                    }
                )
            if spec["status"] == "FINALIZED":
                history_entries.append(
                    {
                        "from_status": "MOM_GENERATED",
                        "to_status": "FINALIZED",
                        "changed_by_user_id": user_ids["MOM"],
                        "changed_by_role": "MOM",
                        "reason": "MoM finalized and published.",
                        "created_at": created_at + timedelta(days=7),
                    }
                )

            await replace_status_history(db, app_id, history_entries)

            await db.execute(
                text("DELETE FROM meeting_applications WHERE application_id = :app_id"),
                {"app_id": app_id},
            )
            await db.execute(
                text("DELETE FROM moms WHERE application_id = :app_id"),
                {"app_id": app_id},
            )
            await db.execute(
                text("DELETE FROM gists WHERE application_id = :app_id"),
                {"app_id": app_id},
            )

            if spec["status"] == "EDS":
                await upsert_eds(db, app_id, user_ids["SCRUTINY"], resolved=False)
            elif spec["status"] in {"REFERRED", "MOM_GENERATED", "FINALIZED"}:
                await upsert_eds(db, app_id, user_ids["SCRUTINY"], resolved=True)

            if spec["status"] in {"REFERRED", "MOM_GENERATED", "FINALIZED"}:
                meeting_key = "EAC-95" if spec["status"] == "FINALIZED" else "EAC-96"
                await upsert_referral(
                    db,
                    app_id,
                    meeting_ids[meeting_key],
                    user_ids["SCRUTINY"],
                    "Detailed technical scrutiny completed; recommended for EAC deliberation.",
                )

            if spec["status"] in {"MOM_GENERATED", "FINALIZED"}:
                gist_id = await upsert_gist(
                    db,
                    app_id,
                    user_ids["SCRUTINY"],
                    f"Auto-generated gist for {spec['project_name']} with risk {spec['risk_level']}.",
                )
                await upsert_mom(
                    db,
                    app_id,
                    gist_id,
                    created_by=user_ids["MOM"],
                    finalized_by=user_ids["MOM"] if spec["status"] == "FINALIZED" else None,
                    status="FINALIZED" if spec["status"] == "FINALIZED" else "DRAFT",
                )

            await append_audit_snapshot(
                db,
                actor_id=user_ids["ADMIN"],
                actor_role="ADMIN",
                app_id=app_id,
                status=spec["status"],
            )

        await db.commit()

        summary_tables = [
            "users",
            "applications",
            "application_documents",
            "payments",
            "eds_requests",
            "eds_issues",
            "meetings",
            "meeting_applications",
            "gists",
            "moms",
            "audit_logs",
        ]

        print("\nDemo data seeding complete.")
        print("Credentials:")
        for u in DEMO_USERS:
            print(f"  {u.role:<9} {u.email:<24} / {u.password}")

        print("\nRow counts:")
        for table in summary_tables:
            count = await scalar(db, f"SELECT count(*) FROM {table}")
            print(f"  {table:<24} {count}")

    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(seed_demo_data())
