DOCUMENT_CHECKLISTS: dict[str, list[str]] = {
    "LIMESTONE": [
        "Processing Fees Details",
        "Pre-feasibility report",
        "EMP",
        "Form 1 / 1-M / CAF",
        "District Survey Report (DSR) / Sand Replenishment Study",
        "Land documents (B-1 P-2)",
        "Consent of the concerned landowner(s)",
        "LOI",
        "Lease Deed",
        "Previously issued EC (Environmental Clearance)",
        "Actions taken to comply of EC",
        "Past Production data certified by mining department (Latest)",
        "NOC from Gram Panchayat/local body",
        "200 meter certificate",
        "500 meter certificate",
        "Mining plan approval letter",
        "Approved Mining Plan",
        "Forest NOC regarding nearest forest area (Reserved forest and Protected forest), National Park, Wildlife Sanctuary, and Biodiversity Zone",
        "Complete tree plantation work as per previously issued EC",
        "Water NoC (CGWA)",
        "CTE / CTO from CECB",
        "Geo-tagged Photographs from all directions of project area",
        "7.5 meter wide boundary strip has been excavated or not (If yes, submit restoration plan)",
        "Drone video (pen drive)",
        "KML File",
        "CCR (Certified compliance report)",
        "C.E.M.P.",
        "CER details with consent of gram Sabha/concerned Dept.",
        "All Affidavits",
        "EIA Report and Public Hearing (If Applicable)",
        "GIST Submission (https://sites.google.com/view/ec-tor-form-submission/gist-submission-page)",
    ],
    "SAND": [
        "Processing Fees Details",
        "Pre-feasibility report",
        "EMP",
        "Form 1 / 1-M / CAF",
        "District Survey Report (DSR) / Sand Replenishment Study",
        "Land documents (B-1 P-2)",
        "LOI",
        "NOC from Gram Panchayat/local body",
        "200 meter certificate",
        "500 meter certificate",
        "Marked & Delimited",
        "Mining plan approval letter",
        "Approved Mining Plan",
        "Forest NOC regarding nearest forest area (Reserved forest and Protected forest), National Park, Wildlife Sanctuary, and Biodiversity Zone",
        "KML File",
        "CER details with consent of gram Sabha/concerned Dept.",
        "All Affidavits",
        "GIST Submission (https://sites.google.com/view/ec-tor-form-submission/gist-submission-page)",
    ],
    "BRICKS": [
        "Processing Fees Details",
        "Pre-feasibility report",
        "EMP",
        "Form 1 / 1-M / CAF",
        "District Survey Report (DSR)",
        "Land documents (B-1 P-2)",
        "Consent of the concerned landowner(s)",
        "LOI",
        "Lease Deed",
        "Previously issued EC (Environmental Clearance)",
        "Actions taken to comply of EC",
        "Past Production data certified by mining department (Latest)",
        "NOC from Gram Panchayat/local body",
        "Panchnama",
        "200 meter certificate",
        "500 meter certificate",
        "Mining plan approval letter",
        "Approved Mining Plan",
        "Forest NOC regarding nearest forest area (Reserved forest and Protected forest), National Park, Wildlife Sanctuary, and Biodiversity Zone",
        "Complete tree plantation work as per previously issued EC",
        "Water NoC (CGWA)",
        "CTE / CTO from CECB",
        "Geo-tagged Photographs from all directions of project area",
        "1.0 meter wide boundary strip has been excavated or not (If yes, submit restoration plan)",
        "Drone video (pen drive)",
        "KML File",
        "CCR (Certified compliance report)",
        "C.E.M.P.",
        "CER details with consent of gram Sabha/concerned Dept.",
        "All Affidavits",
        "EIA Report and Public Hearing (If Applicable)",
        "GIST Submission (https://sites.google.com/view/ec-tor-form-submission/gist-submission-page)",
    ],
    "INFRASTRUCTURE": [
        "Processing Fees Details",
        "Pre-feasibility report",
        "EMP",
        "Form 1 / 1-M / CAF",
        "Land documents (B-1 P-2)",
        "Previously issued EC (Environmental Clearance)",
        "Actions taken to comply of EC",
        "Partnership deed/Consent of owner(s)",
        "Conceptual Plan",
        "Approved Layout from town and country planning",
        "Land Use / Zoning Map",
        "Built-up Area Statement",
        "Building permission",
        "Water Permission (NRANVP/CGWA)",
        "STP Design & Reuse Plan / Disinfection Proposal",
        "Solid Waste Management Plan",
        "Solar Energy Plan",
        "Green Belt Area statement",
        "EMP Cost Estimates",
        "NBWL Clearance (if <1km)",
        "Fire NOC",
        "Aviation NOC",
        "Wildlife Management Plan (If applicable)",
        "CTE / CTO from CECB",
        "Geo-tagged Photographs from all directions of project area",
        "KML File",
        "CER details with consent of gram Sabha/concerned Dept.",
        "All Affidavits",
        "EIA Report and Public Hearing (If Applicable)",
        "GIST Submission (https://sites.google.com/view/ec-tor-form-submission/gist-submission-page)",
    ],
    "INDUSTRY": [
        "Processing Fees Details",
        "Pre-feasibility report",
        "EMP",
        "Form 1 / 1-M / CAF",
        "Land documents (B-1 P-2)",
        "Consent of the concerned landowner(s)",
        "Lease Deed",
        "Previously issued EC (Environmental Clearance)",
        "Actions taken to comply of EC",
        "Past Production data certified by mining department (Latest)",
        "NOC from Gram Panchayat/local body",
        "Forest NOC regarding nearest forest area (Reserved forest and Protected forest), National Park, Wildlife Sanctuary, and Biodiversity Zone",
        "Complete tree plantation work as per previously issued EC",
        "Land Use breakup details",
        "ETP",
        "Fire NOC",
        "Water Permission (NRANVP/CGWA)",
        "Water NoC (CGWA)",
        "STP Design & Reuse Plan / Disinfection Proposal",
        "EMP Cost Estimates",
        "CTE / CTO from CECB",
        "ToR Granted",
        "EIA Report and Public Hearing (If Applicable)",
        "Wildlife Management Plan (If applicable)",
        "Affidavit on pending Litigation",
        "All compliance affidavits",
        "Drone video (pen drive)",
        "CCR (Certified compliance report)",
        "C.E.M.P.",
        "CER details with consent of gram Sabha/concerned Dept.",
        "GIST Submission (https://sites.google.com/view/ec-tor-form-submission/gist-submission-page)",
    ],
}


def get_document_checklist_categories() -> list[str]:
    return sorted(DOCUMENT_CHECKLISTS.keys())


def get_document_checklist_for_category(category: str) -> list[dict]:
    key = (category or "").strip().upper()
    items = DOCUMENT_CHECKLISTS.get(key, [])
    return [
        {
            "s_no": idx + 1,
            "document_required": item,
            "remarks": "",
        }
        for idx, item in enumerate(items)
    ]
